--- #YAML:1.0
name:               Map-Copy
version:            0.001_001
abstract:           copy a scalar/array to another, translating it along the way in a map-ish fashion
author:
    - Todd E Rinaldo <toddr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0
resources:
    homepage:    http://wiki.github.com/toddr/perl-Map-Copy/
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/perl-Map-Copy
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
